apiVersion: v1
kind: Secret
metadata:
  name: todolist-secret
  namespace: todolist-grupo-05
  labels:
    app: todolist
    component: secret
  annotations:
    description: "Credenciais e tokens sensíveis do TodoList"
type: Opaque
data:
  ADMIN_USER: YWRtaW4=
  ADMIN_PASSWORD: dHJvcXVlLWVzdGEtc2VuaGE=
  CLEANUP_TOKEN: dHJvcXVlLWVzdGUtdG9rZW4=
  SESSION_KEY: dHJvcXVlLWVzdGUtdmFsb3I=
